<h1><center><b><u>DATA SCIENCE</u></b></center></h1>

In [45]:
print("goodbye world")

goodbye world


                                                                    goodbye world

<h2><u>NUMPY</u></h2>

<h3>METHODS AND STUFF</h3>

In [3]:
import numpy as np
_a = np.array([[1, 2, 3], [4, 5, 6]])                           #the 2d thingy
print(_a.ndim)                                                  #o/p is 2

_b = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(_b.ndim)

print(_b[1, 0, 2])

2
3
3


<h3>.shape()<h3>

So what does the shape do. Now look at this.

In [4]:
_b.shape

(2, 2, 3)

As seen it returned a tuple, since "_b" is the three dimensional array we see that result. The first element of the tuple is the number of the two dimensional array as the "_b" is the 3d array the next in hierarchy is any 2d object, hence the first digit shows that the 3d array has two 2d arrays and the next 2 is the number that shows the number of the 1d arrays in the 2d array, as seen by the pattern it is so obvious that the numbers are in the order of the hierarcy of the data structure array downwards. And the number 3 says that each 1d array contains 3 elements as simple as that.

<h3>.ndim</h3>

In [5]:
#now look at this
B = np.array([0])
B.ndim

1

Since one element hence the dimension is also 1 ffs.
Now lets do the small thingy about knowing a size and all of the array through "numpy" methods

In [8]:
_b.size     #o/p since no of elem
_b.nbytes   #o/p since total size


48

Stuff about ↓
Numpy(np.arange, reshape, random)

→ np.arrange: creates array starting from the zero upto the number specified as arg
→ random is random bro nothing diff same as python w/o numpy



<h3>.arange</h3>

In [11]:
#np.arange
a = np.arange(100)
print(a)

a = np.arange(20, 100) #stuff can be given a starting thing
print(a)

a = np.arange(20, 100, 3) # now this will jump 3 numbers
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67
 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91
 92 93 94 95 96 97 98 99]
[20 23 26 29 32 35 38 41 44 47 50 53 56 59 62 65 68 71 74 77 80 83 86 89
 92 95 98]


<h3>.random</h3>

In [12]:
#np.random.permutation

a = np.random.permutation(np.arange(10))
print(a)

[9 6 2 7 1 4 3 8 5 0]


In the above thingy, first off random is the whole thingy and then the permuation is sub thingy of the random thingy. so the above thing is just returning an aray of the 10 elements and completely arranged in random order.

In [17]:
#np.random.randint → outputting random number b/w 20 and 30
v = np.random.randint(20, 30)
print(v)
print(type(v))



28
<class 'int'>


In [2]:
#random array using numpy
import numpy as np
a = np.random.rand(1000)


Simple thing.

In [3]:
import matplotlib.pyplot as plt


Another random matrix generation.

In [3]:
c = np.random.rand(2, 3)
print(c)

[[0.95901512 0.10982806 0.29469139]
 [0.18982306 0.02156462 0.88787429]]


In [5]:
print(c.ndim)

2


<h3>.reshape</h3>

In [6]:
d = np.arange(100).reshape(4, 25)
print(d)
print(d.shape)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]
 [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49]
 [50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
  74]
 [75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98
  99]]
(4, 25)


Another take on ".reshape".

In [7]:
d = np.arange(100).reshape(4, 5, 5)
print(d)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]

 [[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]
  [70 71 72 73 74]]

 [[75 76 77 78 79]
  [80 81 82 83 84]
  [85 86 87 88 89]
  [90 91 92 93 94]
  [95 96 97 98 99]]]


<h3>SLICING</h3>

Slicing in the numpy is same as that of the slicing in the normal list, but the array defined by the normal list like built-in python library stuff and you store sliced array in another array then the array which is storing the sliced array is rather a copy of the array which was sliced and hence changes to it will not have any effect on the original array. While if you do the same to the array which was defined by the numpy library then the changes done to the array storing the sliced elem' of the array will also incur changes to the original array, this is something that must be remembered throughout the lifetime even when you are on your deathbed given that you stay healthy and die of old age.

In [9]:
a = np.arange(100)
b = a[3:10]
print(b)

[3 4 5 6 7 8 9]


Now to justify what all i typed above.

In [10]:
b[0] = -1200
print(a)

[    0     1     2 -1200     4     5     6     7     8     9    10    11
    12    13    14    15    16    17    18    19    20    21    22    23
    24    25    26    27    28    29    30    31    32    33    34    35
    36    37    38    39    40    41    42    43    44    45    46    47
    48    49    50    51    52    53    54    55    56    57    58    59
    60    61    62    63    64    65    66    67    68    69    70    71
    72    73    74    75    76    77    78    79    80    81    82    83
    84    85    86    87    88    89    90    91    92    93    94    95
    96    97    98    99]


If you notice properly you will see that the og array changed too..

In [13]:
b = a[3:10].copy()
print(b)
b[0] = 1010
print(b)
print(a)

[-1200     4     5     6     7     8     9]
[1010    4    5    6    7    8    9]
[    0     1     2 -1200     4     5     6     7     8     9    10    11
    12    13    14    15    16    17    18    19    20    21    22    23
    24    25    26    27    28    29    30    31    32    33    34    35
    36    37    38    39    40    41    42    43    44    45    46    47
    48    49    50    51    52    53    54    55    56    57    58    59
    60    61    62    63    64    65    66    67    68    69    70    71
    72    73    74    75    76    77    78    79    80    81    82    83
    84    85    86    87    88    89    90    91    92    93    94    95
    96    97    98    99]


More on this

In [14]:
b = a[::5]
print(b)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [15]:
b = a[::-5]
print(b)

[99 94 89 84 79 74 69 64 59 54 49 44 39 34 29 24 19 14  9  4]


In [16]:
b = a[::-1] #reversing of the array
print(b)

[   99    98    97    96    95    94    93    92    91    90    89    88
    87    86    85    84    83    82    81    80    79    78    77    76
    75    74    73    72    71    70    69    68    67    66    65    64
    63    62    61    60    59    58    57    56    55    54    53    52
    51    50    49    48    47    46    45    44    43    42    41    40
    39    38    37    36    35    34    33    32    31    30    29    28
    27    26    25    24    23    22    21    20    19    18    17    16
    15    14    13    12    11    10     9     8     7     6     5     4
 -1200     2     1     0]


down below is what you call finding out the index of the element in the numpy array.

In [26]:
idx = np.where(a == -1200)[0][0]
print(idx)
a[idx] = 3
print(a)

3
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [28]:
a = np.round(10*np.random.rand(5, 4))
print(a)

[[ 2.  1. 10.  4.]
 [ 7.  6.  6.  2.]
 [ 1.  8.  1.  8.]
 [ 9.  9. 10.  6.]
 [10.  2.  5.  7.]]


In [33]:
print(a[1, 2]) #prints the specific elem
print(a[1, :]) #prints the whole second array in the matrix
print(a[:, 1]) #prints the second column
print(a[1:3, 2:4])

6.0
[7. 6. 6. 2.]
[1. 6. 8. 9. 2.]
[[6. 2.]
 [1. 8.]]


<h3>.T</h3>
Transposing of the matrix.

In [34]:
print(a.T)


[[ 2.  7.  1.  9. 10.]
 [ 1.  6.  8.  9.  2.]
 [10.  6.  1. 10.  5.]
 [ 4.  2.  8.  6.  7.]]


<h3>LINEAR ALGEBRA IN NUMPY</h3>

In [36]:
import numpy.linalg as la

In [37]:
print(la.inv(np.random.rand(3, 3))) #inversing of the matrix in linalg

[[ 133.5086634  -119.11177914 -133.38872541]
 [  32.19346821  -31.85104426  -30.82635156]
 [ -83.19789039   78.51632161   82.97073044]]


<h3>Sorting</h3>


In [39]:
a.sort(axis = 0) #sorts by column
print(a)
a.sort(axis = 1) #sorts by rows 
print(a)

[[ 1.  1.  1.  2.]
 [ 2.  2.  5.  4.]
 [ 7.  6.  6.  6.]
 [ 9.  8. 10.  7.]
 [10.  9. 10.  8.]]
[[ 1.  1.  1.  2.]
 [ 2.  2.  4.  5.]
 [ 6.  6.  6.  7.]
 [ 7.  8.  9. 10.]
 [ 8.  9. 10. 10.]]


<h3>more indexing</h3>
this is also called masking, or something close i dont remember clearly

In [41]:
a = np.arange(100)
b = a[[3, 5, 6]]
print(b)
b[0] = -4           #this is more like copy rather than a view
print(b)
print(a)

[3 5 6]
[-4  5  6]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [44]:
b = a[a<40]
print(b)
b = a[(a<40) & (a>30)]
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[31 32 33 34 35 36 37 38 39]


<h3>Broadcasting</h3>
this is like the algebra of the matrices made easy by numpy. i will read documentation and code the thingy.

In [48]:
a = np.round(10*np.random.rand(2, 3))
print(a)
a = a +3
print(a)
a = a + (np.arange(2).reshape(2, 1))
print(a)

[[2. 9. 9.]
 [4. 3. 2.]]
[[ 5. 12. 12.]
 [ 7.  6.  5.]]
[[ 5. 12. 12.]
 [ 8.  7.  6.]]


In [51]:
b = np.round(10*np.random.rand(2, 2))
print(b)

c = np.hstack((a, b)) # concantenates matrix a and b
print(c)

[[8. 9.]
 [2. 1.]]
[[ 5. 12. 12.  8.  9.]
 [ 8.  7.  6.  2.  1.]]


In [55]:
a = np.random.permutation(np.arange(10))
print(a)
#a.sort()
#print(a)  #built in python function
print(np.sort(a))
 

[9 0 7 6 4 3 8 2 5 1]
[0 1 2 3 4 5 6 7 8 9]


In [56]:
a = np.array(["abc", "how are you", "u765", "13er"])
print(a)
a.sort()
print(a)

['abc' 'how are you' 'u765' '13er']
['13er' 'abc' 'how are you' 'u765']


<h3>Speed of the universal functions</h3>

In [57]:
b = np.random.rand(1000000)
%timeit sum(b)
%timeit np.sum(b)

80.2 ms ± 1.68 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.31 ms ± 92.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [58]:
def mysum(G):
    s = 0
    for x in G:
        s+=x
    return s

In [59]:
%timeit mysum(b)

110 ms ± 4.41 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


<h2>PANDAS</h2>

In [15]:
import pandas as pd

a = pd.Series([2, 3, 4, 5], index = ['a', 'b', 'c', 'd'])

print(a.values)
print(type(a.values))
print(type(a))


[2 3 4 5]
<class 'numpy.ndarray'>
<class 'pandas.core.series.Series'>


In [16]:
print(a.index)
a['a']

Index(['a', 'b', 'c', 'd'], dtype='object')


2

In [17]:
a['a': 'c']

a    2
b    3
c    4
dtype: int64

In [18]:
grade_dict = {'A': 4, 'B': 3.5, 'C': 3, 'D': 2.5}
grads = pd.Series(grade_dict)

grads.values

array([4. , 3.5, 3. , 2.5])

<h3>.Series</h3>
these are good for 1d array but not so cool for the 2d arrays or in general multidimensional array.

In [19]:
marks_dict = {'A': 85, 'B': 75, 'C': 65, 'D': 55}
marks = pd.Series(marks_dict)
print(marks)

A    85
B    75
C    65
D    55
dtype: int64


In [20]:
marks['A']

85

In [21]:
marks[0:2]

A    85
B    75
dtype: int64

<h3>DataFrame</h3>

In [22]:
grads 

A    4.0
B    3.5
C    3.0
D    2.5
dtype: float64

its basically adding on some more on top of the dictionary and then making it even cooler in like when you look at it and all

In [23]:
d = pd.DataFrame({'Marks': marks, 'Grades': grads})
d

Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

In [24]:
d.T

A     B     C     D
Marks   85.0  75.0  65.0  55.0
Grades   4.0   3.5   3.0   2.5

In [25]:
d.values

array([[85. ,  4. ],
       [75. ,  3.5],
       [65. ,  3. ],
       [55. ,  2.5]])

In [26]:
d.values[2, 0]

65.0

In [27]:
d.columns

Index(['Marks', 'Grades'], dtype='object')

In [28]:
d

Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

85 - 100
x - 90

adding columns in the given data frame and all, and also deleting them

In [30]:
d['ScaledMarks'] = d['Marks']*90/100
d

Marks  Grades  ScaledMarks
A     85     4.0         76.5
B     75     3.5         67.5
C     65     3.0         58.5
D     55     2.5         49.5

In [32]:
del d['ScaledMarks']
d

Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

its like that easy to filter the data according to the need and all this is a very simple thing to do. and this is called <b><u>masking</u></b>

In [38]:
g = d[d['Marks'] > 70]
g

Marks  Grades
A     85     4.0
B     75     3.5

<h3>Pandas(NaN)<h3>

In [4]:
a = pd.DataFrame([{'a':1, 'b': 4}, {'b': -3, 'c': 9}])
a

a  b    c
0  1.0  4  NaN
1  NaN -3  9.0

In [5]:
a.fillna(0)

a  b    c
0  1.0  4  0.0
1  0.0 -3  9.0

<h3>Indexing</h3>
Sometimes the time arises where there is the use of the indices to call out some of the series object in the pandas, 
for ex: 
    consider, 
    data = pd.Series(['a', 'b', 'c'], index = [1, 3, 5])
    now, 
    if you call out data[1] #explicit index, means it refers to the explicit index
    but, 
    when you call out data[1:3] there is the confusion of what actual indices is really being accessed
    hence there are some functions that are used like "loc" and "iloc".

    loc = explicit index
    iloc = implicit index

In [5]:
a = pd.Series(['a', 'b', 'c'], index = [1, 3, 5])
a[1]

'a'

In [6]:
a[1:3]

3    b
5    c
dtype: object

In [7]:
a.loc[1:3]

1    a
3    b
dtype: object

In [33]:
d

Marks  Grades
A     85     4.0
B     75     3.5
C     65     3.0
D     55     2.5

In [34]:
d.iloc[2:]

Marks  Grades
C     65     3.0
D     55     2.5

In [35]:
import numpy as np